# Custom Language File for Launcher Customizer

[ejs.app]
title = "Creatopico Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Creatopico"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@creatopico_official"
mediaDiscordURL = "https://discord.gg/AwKR2q9qU2"

[ejs.settings]
sourceGithubLink = "https://github.com/Creatopico"
supportLink = "https://github.com/Creatopico"

[ejs.welcome]
welcomeHeader = "Добро пожаловать на Creatopico!"
welcomeDescription = "Приватный Minecraft сервер с модом Create"
welcomeDescCTA = ""
